version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  airflow-standalone:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: etl_airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=<YOUR_FERNET_KEY_HERE>
      - PYTHONPATH=/opt/airflow
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
    ports:
      - "8082:8080"
    command: standalone


volumes:
  pgdata: